export default {
    // hospital_name: '',
    // hospital_account: '',
    qykfcws: '全院开放床位数（张）',
    qyzzjhbfcws: '全院重症监护病房床位数（张）',
    qyzchszs: '全院注册护士总数（人）',
    wzchszs: '未注册护士总数（人）',
    cshlgzhszs: '从事护理工作护士总数（人）',
    cshlgzdhlryzqywsjsrydbl: '从事护理工作的护理人员占全院卫生技术人员的比例（%）',
    lcgwhszs: '临床岗位护士总数（人）',
    qybqzchszs: '全院病区注册护士总数（人）',
    bqhsysjkfcwbl: '病区护士与实际开放床位比例（%）',
    zzjhbfhszs: '重症监护病房护士总数（人）',
    zzjhbfhsysjkfcwbl: '重症监护病房护士与实际开放床位比例（%）',
    ccubfhszs: 'CCU病房护士总数（人）',
    ccubfhsysjkfcwbl: 'CCU病房护士与实际开放床位比例（%）',
    ssshszs: '手术室护士总数（人）',
    ssshsysjkfssjbl: '手术室护士与实际开放手术间比例（%）',
    txshszs: '透析室护士总数（人）',
    txshsytxjbl: '透析室护士与透析机比例（%）',
    qnlzhszs: '全年离职护士总数（人）',
    qybsxlhss: '全院博士学历护士数（人）',
    ssxlhss: '硕士学历护士数（人）',
    ssysxlhszqyhsbl: '硕士以上学历护士占全院护士比例（%）',
    qybkxlhss: '全院本科学历护士数（人）',
    bkxlhszbqyhsbl: '本科学历护士占比全院护士比例（%）',
    qydzxlhss: '全院大专学历护士数（人）',
    dzxlhszbqqhsbl: '大专学历护士占比全院护士比例（%）',
    qyzzxlhss: '全院中专学历护士数（人）',
    zzxlhszbqyhsbl: '中专学历护士占比全院护士比例（%）',
    hlglrybkysxlbl: '护理管理人员本科以上学历比例(%)',
    zyyxbyhzyhlzybyhss: '中医院校毕业和中医护理专业毕业护士数（人）',
    zzyxbyhzyhlzybyhszqyhsbl: '中医院校毕业和中医护理专业毕业护士占全院护士比例（%）',
    qyzrhszs: '全院主任护师总数（人）',
    fzrhszs: '副主任护师总数（人）',
    qygzchsbl: '全院高级职称护士比例（%）',
    qyzghszs: '全院主管护师总数（人）',
    qyzjzchsbl: '全院中级职称护士比例（%）',
    qyhszs: '全院护师总数（人）',
    qyhszs2: '全院护士总数（人）',
    qycjzchsbl: '全院初级职称护士比例（%）',
    hlryxtjszyyzshjngwpxdbl: '护理人员系统接受中医药知识和技能岗位培训（3年培训时间≥100学时）的比例（%）',
    wpjxwyzs: '外派进修人员总数（人）',
    qyyzkhszgrzzrs: '全院有专科护士资格认证总人数（人）',
    zkhszqyhsbl: '专科护士占全院护士比例（%）',
    zzjhzkhszs: '重症监护专科护士总数（人）',
    xyjhzkhszs: '血液净化专科护士总数（人）',
    zlzkhszs: '肿瘤专科护士总数（人）',
    ssszkhszs: '手术室专科护士总数（人）',
    jzjjzkhszs: '急诊急救专科护士总数（人）',
    gkzkhszs: '骨科专科护士总数（人）',
    jlzkhszs: '静疗专科护士总数（人）',
    tnbzkhszs: '糖尿病专科护士总数（人）',
    xdgyzxzkhszs: '消毒供应中心专科护士总数（人）',
    qita: '其他（请在备注栏注明 ）',
    hlzlgljg: '护理质量管理架构',
    sfjlhlzlglwyh: '是否建立护理质量管理委员会',
    kzhlxxhjs: '开展护理信息化建设',
    lchlxxxt: '临床护理信息系统',
    hlglxt: '护理管理系统',
    qybqzs: '全院病区总数（个）',
    qysszrzzthlfwmsbqs: '全院实施责任制整体护理服务模式病区数（个）',
    zrzzthlfwbqzqybqsbl: '责任制整体护理服务病区占全院病区数比例（%）',
    yywyzhlfwsfyy: '医院为优质护理服务示范医院',
    kswyzhlfwsfbq: '科室为优质护理服务示范病区（个）',
    // kswyzhlfwsfbq_desc: '',
    kswyzhlfwsfbq2: '科室为优质护理服务示范病区 （个）',
    // kswyzhlfwsfbq2_desc: '',
    sfwglbhlzkpxjd: '是否为各类别护理专科培训基地（基地名称请在备注栏注明）',
    // sfwglbhlzkpxjd_desc: '',
    sfwglbhlzkpxjd2: '是否为各类别护理专科培训基地（基地名称请在备注栏注明）',
    // sfwglbhlzkpxjd2_desc: '',
    qylsgjzyygljzdzkhlfabzs: '全院落实国家中医药管理局重点专科护理方案病种数（个）',
    yyzdzyhlfasl: '医院制定中医护理方案数量（个）',
    qyzyhljskzxms: '全院中医护理技术开展项目数（项）',
    qnzyhljskzzlt: '全年中医护理技术开展总例数（例）',
    qyhllcdjlsrs: '全院护理临床带教老师人数（人）',
    qymnjssxsrs: '全院每年接收实习生人数（人）',
    mnjsbkjyssxsrs: '每年接收本科及以上实习生人数（人）',
    mnjszyyxhzyhlzysxsrs: '每年接收中医院校和中医护理专业实习生人数（人）',
    mnjsjxhsrs: '每年接收进修护士人数（人）',
    gjjzykt: '国家级在研课题 （项)',
    ljjzykthdjf: '国家级在研课题获得经费 （万元）',
    sbjzykt: '省部级在研课题（项）',
    sbjzykthdjf: '省部级在研课题获得经费（万元）',
    sj: '市级（含大学、科学院）（项）',
    sjhdjf: '市级（含大学、科学院）获得经费（万元）',
    qjzykt: '区级在研课题 （项）',
    qjzykthdjf: '区级在研课题获得经费（万元））',
    yjzykt: '院级在研课题（项）',
    yjzykthdjf: '院级在研课题获得经费 （万元',
    hdkycgxm: '获得科研成果项目（项）请在备注栏注明',
    hxqkfbwz: '核心期刊发表文章（篇）',
    scisllws: 'SCI收录论文数（篇）',
    drzbcbzz: '担任主编出版著作（部）著作名称请在备注栏注明',
    // drzbcbzz_desc: '',
    cbzz: '参编著作（部）著作名称请在备注栏注明',
    // cbzz_desc: ''
}